FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV STREAMLIT_SERVER_ADDRESS=0.0.0.0
ENV STREAMLIT_SERVER_PORT=8501

WORKDIR /app

COPY requirements_frontend.txt .
RUN pip install --no-cache-dir -r requirements_frontend.txt

COPY .streamlit ./.streamlit
COPY frontend ./frontend
COPY streamlit_app.py style.css ./

EXPOSE 8501

CMD ["python", "-m", "streamlit", "run", "streamlit_app.py"]
