name: "svtr_ocr_onnx"
platform: "onnxruntime_onnx"
max_batch_size: 2

input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [1, 32, 512]
  }
]

output [
  {
    name: "log_probs"
    data_type: TYPE_FP32
    dims: [128, 53]
  }
]

dynamic_batching {
  preferred_batch_size: [2]
  max_queue_delay_microseconds: 1000
}

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]
